### ISSUE TITLE
How to install this module?

### ISSUE THREAD

**Issue by yunhwankim2** [rbaravalle/imfractal#2]
Hi. Thanks for nice code.
I just want to know how to install this module into my machine. I tried to use pip with git+, but there is no setup.py file so I failed.
Could you let me know how to install your module?
Thank you.

Yun

**Comment by rbaravalle** [comment]
Hi, sorry for the delay. The library needs serious refactoring right now, so I think it is not worth to make it installable. I suggest you clone it and use the tests locally, sorry for this.

**Comment by yunhwankim2** [comment]
Okay, I see. Thank you for reply.
